### ISSUE TITLE
jajajajjaja

### ISSUE THREAD

**Issue by PiluVitu** [GabrielTrindadeC/mecanica-front#42]
Try n da ? A Mi Gã O

**Comment by GabrielTrindadeC** [comment]
Obrigado por abrir a issue. 
 Verifique os nossos guidelines, Código de conduta: https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md; 
 Contribuição:https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md; 
 Guia de Estilo: https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md;

**Comment by GabrielTrindadeC** [comment]
eu quero!!!

**Comment by GabrielTrindadeC** [comment]
issue inativa
